// @custom
// Prove marker checks accept ordinary edits, moves, and declaration removal.
import assert from 'node:assert/strict'
import test from 'node:test'
import { checkCustom } from '../scripts/check-custom.js'

const marked = '// @custom\n// Read local credentials.\nexport const version = 1\n'
const read = (files: Record<string, string>) => (path: string): string => {
  const content = files[path]
  assert.ok(content !== undefined, `missing fixture ${path}`)
  return content
}

test('unmarked custom code fails while arbitrary marked edits remain editable', () => {
  assert.equal(checkCustom(['auth.ts'], read({ 'auth.ts': 'export const version = 1' })).length, 1)
  assert.deepEqual(checkCustom(['auth.ts'], read({ 'auth.ts': marked })), [])
  assert.deepEqual(checkCustom(['auth.ts'], read({ 'auth.ts': marked.replace('= 1', '= 2') })), [])
  assert.equal(checkCustom(['auth.ts'], read({ 'auth.ts': '// @custom\nexport const version = 1' })).length, 1)
})

test('file moves and deletion work when declarations change in the same commit', () => {
  assert.deepEqual(checkCustom(['auth/session.ts'], read({ 'auth/session.ts': marked })), [])
  assert.deepEqual(checkCustom([], read({})), [])
})

test('files outside the declaration list are not checked', () => {
  const generated = '// File generated by Scalar.\nexport const version = 2\n'
  assert.deepEqual(checkCustom([], read({ 'sdk.ts': generated })), [])
  assert.deepEqual(checkCustom(['sdk.ts'], read({ 'sdk.ts': generated + marked })), [])
  assert.deepEqual(checkCustom([], read({ 'sdk.ts': generated })), [])
})

test('marker text inside a string and empty comments do not declare ownership', () => {
  for (const source of ['const example = `\n' + marked + '`', '// @custom\n/** */\nexport {}']) {
    assert.equal(checkCustom(['auth.ts'], read({ 'auth.ts': source })).length, 1)
  }
})
