// File generated from our OpenAPI spec by Scalar. See README.md for details.

import type { Command } from 'commander';
import SDK from '../sdk/index';
import {
  createProgram,
  type CliClientOptionDefinition,
  type CliCommandDefinition,
  type CliCommandGroup,
} from '../cli/runtime';
import { completions } from '../cli/completions';
import type { CliAuthDefinition } from '../cli/login';
import { addMachineAliases } from '../custom/machines.js';
import { registerFeedbackCommands } from '../feedback/command.js';

const clientOptions = [
  {
    clientKey: 'apiKey',
    sdkKey: 'apiKey',
    name: 'api-key',
    optionKey: 'apiKey',
    env: 'DEDALUS_API_KEY',
    description:
      'Dedalus API key or short-lived delegated access token in Authorization: Bearer <credential>.',
    auth: true,
  },
  {
    clientKey: 'xAPIKey',
    sdkKey: 'xAPIKey',
    name: 'x-api-key',
    optionKey: 'xApiKey',
    env: 'DEDALUS_X_API_KEY',
    description: 'Dedalus API key. Alternative to Bearer token.',
    auth: true,
  },
  {
    clientKey: 'dedalusOrgID',
    sdkKey: 'dedalusOrgID',
    name: 'dedalus-org-id',
    optionKey: 'dedalusOrgId',
    env: 'DEDALUS_ORG_ID',
    description:
      'Optional organization assertion. Must match the organization identified by the API credential.',
    auth: false,
  },
] as const satisfies readonly CliClientOptionDefinition[];

const commands = [
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'list'],
    methodName: 'list',
    summary: 'List machines',
    transport: 'http',
    iterable: true,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: false,
        valueKind: 'integer',
      },
      {
        name: 'cursor',
        optionKey: 'cursor',
        paramKey: 'cursor',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'create'],
    methodName: 'create',
    summary: 'Create machine',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'autosleep',
        optionKey: 'autosleep',
        paramKey: 'autosleep',
        location: 'body',
        required: false,
        description:
          'Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h, 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.',
        valueKind: 'string',
      },
      {
        name: 'memory-mib',
        optionKey: 'memoryMib',
        paramKey: 'memory_mib',
        location: 'body',
        required: false,
        description: 'Memory in MiB.',
        valueKind: 'integer',
      },
      {
        name: 'storage-gib',
        optionKey: 'storageGib',
        paramKey: 'storage_gib',
        location: 'body',
        required: false,
        description: 'Storage in GiB.',
        valueKind: 'integer',
      },
      {
        name: 'vcpu',
        optionKey: 'vcpu',
        paramKey: 'vcpu',
        location: 'body',
        required: false,
        description: 'CPU in vCPUs.',
        valueKind: 'number',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'update'],
    methodName: 'update',
    summary: 'Update machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'autosleep',
        optionKey: 'autosleep',
        paramKey: 'autosleep',
        location: 'body',
        required: false,
        description:
          'Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h, 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.',
        valueKind: 'string',
      },
      {
        name: 'memory-mib',
        optionKey: 'memoryMib',
        paramKey: 'memory_mib',
        location: 'body',
        required: false,
        description: 'Memory in MiB.',
        valueKind: 'integer',
      },
      {
        name: 'storage-gib',
        optionKey: 'storageGib',
        paramKey: 'storage_gib',
        location: 'body',
        required: false,
        description: 'Storage in GiB.',
        valueKind: 'integer',
      },
      {
        name: 'vcpu',
        optionKey: 'vcpu',
        paramKey: 'vcpu',
        location: 'body',
        required: false,
        description: 'CPU in vCPUs.',
        valueKind: 'number',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'delete'],
    methodName: 'delete',
    summary: 'Destroy machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'sleep'],
    methodName: 'sleep',
    summary: 'Sleep a running machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'wake'],
    methodName: 'wake',
    summary: 'Wake a sleeping machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'reboot'],
    methodName: 'reboot',
    summary: 'Reboot a machine with fresh memory',
    description:
      'Checkpoints files and replaces the runtime. The machine ID and filesystem are preserved. RAM, processes, and temporary mounts are cleared. Poll the machine until its phase is running. Retry the same Idempotency-Key after a lost response.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'force',
        optionKey: 'force',
        paramKey: 'force',
        location: 'query',
        required: false,
        description:
          'Recover from the last committed filesystem checkpoint without guest cooperation. Unpublished file writes are lost. The default checkpoints files before rebooting.',
        valueKind: 'boolean',
      },
    ],
  },
  {
    resourcePath: ['machines', 'ssh'],
    commandPath: ['machines:ssh', 'list'],
    methodName: 'list',
    summary: 'List SSH sessions',
    transport: 'http',
    iterable: true,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: false,
        valueKind: 'integer',
      },
      {
        name: 'cursor',
        optionKey: 'cursor',
        paramKey: 'cursor',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'ssh'],
    commandPath: ['machines:ssh', 'create'],
    methodName: 'create',
    summary: 'Create SSH session',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'public-key',
        optionKey: 'publicKey',
        paramKey: 'public_key',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'ssh'],
    commandPath: ['machines:ssh', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get SSH session',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'session-id',
        optionKey: 'sessionId',
        paramKey: 'session_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'ssh'],
    commandPath: ['machines:ssh', 'delete'],
    methodName: 'delete',
    summary: 'Delete SSH session',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'session-id',
        optionKey: 'sessionId',
        paramKey: 'session_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'list'],
    methodName: 'list',
    summary: 'List executions',
    transport: 'http',
    iterable: true,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: false,
        valueKind: 'integer',
      },
      {
        name: 'cursor',
        optionKey: 'cursor',
        paramKey: 'cursor',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'create'],
    methodName: 'create',
    summary: 'Create execution',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'command',
        optionKey: 'command',
        paramKey: 'command',
        location: 'body',
        required: true,
        valueKind: 'array',
      },
      {
        name: 'cwd',
        optionKey: 'cwd',
        paramKey: 'cwd',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'env',
        optionKey: 'env',
        paramKey: 'env',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'stdin',
        optionKey: 'stdin',
        paramKey: 'stdin',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'timeout-ms',
        optionKey: 'timeoutMs',
        paramKey: 'timeout_ms',
        location: 'body',
        required: false,
        valueKind: 'integer',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get execution',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'delete'],
    methodName: 'delete',
    summary: 'Delete execution',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'output'],
    methodName: 'output',
    summary: 'Get execution output',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'events'],
    methodName: 'events',
    summary: 'List execution events',
    transport: 'http',
    iterable: true,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: false,
        valueKind: 'integer',
      },
      {
        name: 'cursor',
        optionKey: 'cursor',
        paramKey: 'cursor',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions', 'logs'],
    commandPath: ['machines:executions:logs', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get execution log status',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions', 'logs'],
    commandPath: ['machines:executions:logs', 'reauthorize'],
    methodName: 'reauthorize',
    summary: 'Reauthorize execution log publication',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions', 'logs'],
    commandPath: ['machines:executions:logs', 'create-token'],
    methodName: 'createToken',
    summary: 'Create execution log read token',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'autoresizing'],
    commandPath: ['machines:autoresizing', 'retrieve'],
    methodName: 'retrieve',
    summary: "Read this machine's RAM autoresizing settings",
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'autoresizing'],
    commandPath: ['machines:autoresizing', 'update'],
    methodName: 'update',
    summary: "Set this machine's RAM autoresizing settings",
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'enabled',
        optionKey: 'enabled',
        paramKey: 'enabled',
        location: 'body',
        required: true,
        valueKind: 'boolean',
      },
    ],
  },
  {
    resourcePath: ['organization', 'autoresizing'],
    commandPath: ['organization:autoresizing', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Read organization RAM autoresizing policy',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [],
  },
  {
    resourcePath: ['organization', 'autoresizing'],
    commandPath: ['organization:autoresizing', 'update'],
    methodName: 'update',
    summary: 'Set organization RAM autoresizing policy',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    authClientKeyRequirements: [['xAPIKey'], ['apiKey']],
    positional: [],
    flags: [
      {
        name: 'enabled',
        optionKey: 'enabled',
        paramKey: 'enabled',
        location: 'body',
        required: true,
        description:
          'Allow automatic RAM increases for all organization machines. Disabling preserves applied RAM and already admitted resizes.',
        valueKind: 'boolean',
      },
    ],
  },
] as const satisfies readonly CliCommandDefinition[];

const groups = [] as const satisfies readonly CliCommandGroup[];

const auth = {
  loginPath: ['login'],
  logoutPath: ['logout'],
  loginCommand: 'dedalus login',
  storeName: 'dedalus',
  storeEnv: 'DEDALUS_CREDENTIALS_FILE',
  baseUrlEnv: 'DEDALUS_BASE_URL',
  backend: 'auto',
  defaultBaseUrl: 'https://dcs.dedaluslabs.ai',
  requirements: [['xAPIKey'], ['apiKey']],
  envByKey: {
    apiKey: 'DEDALUS_API_KEY',
    xAPIKey: 'DEDALUS_X_API_KEY',
  },
  methods: [
    {
      name: 'api-key',
      label: 'Enter your access token',
      kind: 'token',
      clientKey: 'apiKey',
      prompt: 'Access token: ',
    },
    {
      name: 'x-api-key',
      label: 'Enter your API key',
      kind: 'token',
      clientKey: 'xAPIKey',
      prompt: 'API key: ',
    },
  ],
} as const satisfies CliAuthDefinition;

export const getProgram = (): Command =>
  registerFeedbackCommands(addMachineAliases(createProgram({
    SDK,
    binaryName: 'dedalus',
    version: '0.7.0', // x-release-please-version
    description: 'CLI for Dedalus',
    defaultFormat: 'auto',
    defaultErrorFormat: 'auto',
    clientOptions,
    // Feedback owns a positional message and attachment selection instead of generated flags.
    commands: commands.filter((definition: CliCommandDefinition) => definition.resourcePath[0] !== 'feedback'),
    groups,
    completions,
    auth,
  }), clientOptions, { auth }), clientOptions, auth);
