// File generated from our OpenAPI spec by Scalar. See README.md for details.

import type { Command } from 'commander';
import SDK from '../sdk/index';
import {
  createProgram,
  type CliClientOptionDefinition,
  type CliCommandDefinition,
  type CliCommandGroup,
} from '../cli/runtime';
import { completions } from '../cli/completions';
import type { CliAuthDefinition } from '../cli/login';

const clientOptions = [
  {
    clientKey: 'apiKey',
    sdkKey: 'apiKey',
    name: 'api-key',
    optionKey: 'apiKey',
    env: 'DEDALUS_API_KEY',
    description: 'API key authentication using Bearer token',
    auth: true,
  },
  {
    clientKey: 'xAPIKey',
    sdkKey: 'xAPIKey',
    name: 'x-api-key',
    optionKey: 'xApiKey',
    env: 'DEDALUS_X_API_KEY',
    description: 'API key authentication using X-API-Key header',
    auth: true,
  },
  {
    clientKey: 'bearerAuth',
    sdkKey: 'bearerAuth',
    name: 'bearer-auth',
    optionKey: 'bearerAuth',
    env: 'DEDALUS_BEARER_AUTH',
    description:
      'Dedalus API key or short-lived delegated access token in Authorization: Bearer <credential>.',
    auth: true,
  },
  {
    clientKey: 'provider',
    sdkKey: 'provider',
    name: 'provider',
    optionKey: 'provider',
    env: 'DEDALUS_PROVIDER',
    description: 'Provider name for BYOK mode.',
    auth: false,
  },
  {
    clientKey: 'providerKey',
    sdkKey: 'providerKey',
    name: 'provider-key',
    optionKey: 'providerKey',
    env: 'DEDALUS_PROVIDER_KEY',
    description: 'Provider API key for BYOK mode.',
    auth: false,
  },
  {
    clientKey: 'providerModel',
    sdkKey: 'providerModel',
    name: 'provider-model',
    optionKey: 'providerModel',
    env: 'DEDALUS_PROVIDER_MODEL',
    description: 'Model identifier for BYOK provider.',
    auth: false,
  },
] as const satisfies readonly CliClientOptionDefinition[];

const commands = [
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'list'],
    methodName: 'list',
    summary: 'List machines',
    transport: 'http',
    iterable: true,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: false,
        valueKind: 'integer',
      },
      {
        name: 'cursor',
        optionKey: 'cursor',
        paramKey: 'cursor',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'create'],
    methodName: 'create',
    summary: 'Create machine',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'autosleep',
        optionKey: 'autosleep',
        paramKey: 'autosleep',
        location: 'body',
        required: false,
        description:
          'Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h, 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.',
        valueKind: 'string',
      },
      {
        name: 'memory-mib',
        optionKey: 'memoryMib',
        paramKey: 'memory_mib',
        location: 'body',
        required: false,
        description: 'Memory in MiB.',
        valueKind: 'integer',
      },
      {
        name: 'storage-gib',
        optionKey: 'storageGib',
        paramKey: 'storage_gib',
        location: 'body',
        required: false,
        description: 'Storage in GiB.',
        valueKind: 'integer',
      },
      {
        name: 'vcpu',
        optionKey: 'vcpu',
        paramKey: 'vcpu',
        location: 'body',
        required: false,
        description: 'CPU in vCPUs.',
        valueKind: 'number',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'update'],
    methodName: 'update',
    summary: 'Update machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'autosleep',
        optionKey: 'autosleep',
        paramKey: 'autosleep',
        location: 'body',
        required: false,
        description:
          'Idle window before autosleep. Accepts fixed duration units like 30s, 30m, 2h, 7d3h4s, or 1w3d, raw seconds ("1800"), or never to disable.',
        valueKind: 'string',
      },
      {
        name: 'memory-mib',
        optionKey: 'memoryMib',
        paramKey: 'memory_mib',
        location: 'body',
        required: false,
        description: 'Memory in MiB.',
        valueKind: 'integer',
      },
      {
        name: 'storage-gib',
        optionKey: 'storageGib',
        paramKey: 'storage_gib',
        location: 'body',
        required: false,
        description: 'Storage in GiB.',
        valueKind: 'integer',
      },
      {
        name: 'vcpu',
        optionKey: 'vcpu',
        paramKey: 'vcpu',
        location: 'body',
        required: false,
        description: 'CPU in vCPUs.',
        valueKind: 'number',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'delete'],
    methodName: 'delete',
    summary: 'Destroy machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'sleep'],
    methodName: 'sleep',
    summary: 'Sleep a running machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines'],
    commandPath: ['machines', 'wake'],
    methodName: 'wake',
    summary: 'Wake a sleeping machine',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'ssh'],
    commandPath: ['machines:ssh', 'list'],
    methodName: 'list',
    summary: 'List SSH sessions',
    transport: 'http',
    iterable: true,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: false,
        valueKind: 'integer',
      },
      {
        name: 'cursor',
        optionKey: 'cursor',
        paramKey: 'cursor',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'ssh'],
    commandPath: ['machines:ssh', 'create'],
    methodName: 'create',
    summary: 'Create SSH session',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'public-key',
        optionKey: 'publicKey',
        paramKey: 'public_key',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'ssh'],
    commandPath: ['machines:ssh', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get SSH session',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'session-id',
        optionKey: 'sessionId',
        paramKey: 'session_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'ssh'],
    commandPath: ['machines:ssh', 'delete'],
    methodName: 'delete',
    summary: 'Delete SSH session',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'session-id',
        optionKey: 'sessionId',
        paramKey: 'session_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'list'],
    methodName: 'list',
    summary: 'List executions',
    transport: 'http',
    iterable: true,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: false,
        valueKind: 'integer',
      },
      {
        name: 'cursor',
        optionKey: 'cursor',
        paramKey: 'cursor',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'create'],
    methodName: 'create',
    summary: 'Create execution',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'command',
        optionKey: 'command',
        paramKey: 'command',
        location: 'body',
        required: true,
        valueKind: 'array',
      },
      {
        name: 'cwd',
        optionKey: 'cwd',
        paramKey: 'cwd',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'env',
        optionKey: 'env',
        paramKey: 'env',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'stdin',
        optionKey: 'stdin',
        paramKey: 'stdin',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'timeout-ms',
        optionKey: 'timeoutMs',
        paramKey: 'timeout_ms',
        location: 'body',
        required: false,
        valueKind: 'integer',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get execution',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'delete'],
    methodName: 'delete',
    summary: 'Delete execution',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'output'],
    methodName: 'output',
    summary: 'Get execution output',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'executions'],
    commandPath: ['machines:executions', 'events'],
    methodName: 'events',
    summary: 'List execution events',
    transport: 'http',
    iterable: true,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        description: 'Bare, lowercase, hyphenated Machine UUID. Pass the returned machine_id unchanged.',
        valueKind: 'string',
      },
      {
        name: 'execution-id',
        optionKey: 'executionId',
        paramKey: 'execution_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: false,
        valueKind: 'integer',
      },
      {
        name: 'cursor',
        optionKey: 'cursor',
        paramKey: 'cursor',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['machines', 'terminals'],
    commandPath: ['machines:terminals', 'connect'],
    methodName: 'connect',
    transport: 'websocket',
    iterable: true,
    callShape: 'params',
    authClientKeyRequirements: [['apiKey'], ['xAPIKey']],
    positional: [],
    flags: [
      {
        name: 'machine-id',
        optionKey: 'machineId',
        paramKey: 'machine_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'terminal-id',
        optionKey: 'terminalId',
        paramKey: 'terminal_id',
        location: 'path',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'send',
        optionKey: 'send',
        paramKey: 'send',
        location: 'body',
        required: false,
        description: 'JSON message to send after connecting.',
        valueKind: 'unknown',
      },
    ],
  },
] as const satisfies readonly CliCommandDefinition[];

const groups = [] as const satisfies readonly CliCommandGroup[];

const auth = {
  loginPath: ['login'],
  logoutPath: ['logout'],
  loginCommand: 'dedalus login',
  storeName: 'dedalus',
  storeEnv: 'DEDALUS_CREDENTIALS_FILE',
  baseUrlEnv: 'DEDALUS_BASE_URL',
  backend: 'auto',
  defaultBaseUrl: 'https://dcs.dedaluslabs.ai',
  requirements: [['apiKey'], ['xAPIKey']],
  envByKey: {
    apiKey: 'DEDALUS_API_KEY',
    xAPIKey: 'DEDALUS_X_API_KEY',
    bearerAuth: 'DEDALUS_BEARER_AUTH',
  },
  methods: [
    {
      name: 'api-key',
      label: 'Enter your access token',
      kind: 'token',
      clientKey: 'apiKey',
      prompt: 'Access token: ',
    },
    {
      name: 'x-api-key',
      label: 'Enter your API key',
      kind: 'token',
      clientKey: 'xAPIKey',
      prompt: 'API key: ',
    },
    {
      name: 'bearer-auth',
      label: 'Enter your access token',
      kind: 'token',
      clientKey: 'bearerAuth',
      prompt: 'Access token: ',
    },
  ],
} as const satisfies CliAuthDefinition;

export const getProgram = (): Command =>
  createProgram({
    SDK,
    binaryName: 'dedalus',
    version: '0.6.0', // x-release-please-version
    description: 'CLI for Dedalus',
    defaultFormat: 'auto',
    defaultErrorFormat: 'auto',
    clientOptions,
    commands,
    groups,
    completions,
    auth,
  });
